# Generated by Django 5.0.4 on 2024-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0030_passwordconfig_lockout_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='AUTH_METHOD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
