# Generated by Django 5.0.4 on 2024-04-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0034_app_job_pull_app_job_user_log_app_user_sftp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user_sftp',
            name='SETUP_COMPLETE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_list_sftp',
            name='SETUP_COMPLETE',
            field=models.BooleanField(default=False),
        ),
    ]
