# Generated by Django 5.0.4 on 2024-04-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0035_app_user_sftp_setup_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user_sftp',
            name='SFTP_USERNAME',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='hr_list_sftp',
            name='SFTP_USERNAME',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
