# Generated by Django 5.0.4 on 2024-04-23 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0036_app_user_sftp_sftp_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user_sftp',
            name='APP_NAME',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
    ]
