# Generated by Django 5.0.4 on 2024-04-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0037_alter_app_user_sftp_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_job_user_log',
            name='JOB_COMPLETE',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
