# Generated by Django 5.0.4 on 2024-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0038_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_job_pull',
            name='SCHEDULE_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
