# Generated by Django 5.0.4 on 2024-04-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0040_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
  
    ]
