# Generated by Django 5.0.4 on 2024-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0041_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_user_log',
            name='JOB_FILE_DESTINATION',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
