# Generated by Django 5.0.4 on 2024-04-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0042_app_job_user_log_job_file_destination'),
    ]

    operations = [
    
        migrations.AddField(
            model_name='app_job_user_log',
            name='APP_NAME',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
       
    ]
