# Generated by Django 5.0.4 on 2024-04-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0044_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROVISIONINGPOLICY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQ_APPROVAL', models.BooleanField(default=False, null=True)),
                ('REQ_APPROVAL_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('MANAGER_APPROVAL', models.BooleanField(blank=True, default=False, null=True)),
                ('IT_APPROVAL', models.BooleanField(blank=True, default=False, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
        ),
    ]
