# Generated by Django 5.0.4 on 2024-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0045_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
  
        migrations.AlterField(
            model_name='provisioningpolicy',
            name='REQ_APPROVAL',
            field=models.BooleanField(null=True),
        ),
    ]
