# Generated by Django 5.0.4 on 2024-04-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0046_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningpolicy',
            name='BOTH_MANAGER_IT',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningpolicy',
            name='IT_APPROVAL',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningpolicy',
            name='MANAGER_APPROVAL',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
