# Generated by Django 5.0.4 on 2024-04-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0048_remove_terminationpolicy_company_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_roles_filter',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='admin_roles_filter',
            table='ADMIN_ROLE_FILTER',
        ),
        migrations.CreateModel(
            name='ALL_ROLES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROLE_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'ALL_ROLES',
                'managed': True,
            },
        ),
    ]
