# Generated by Django 5.0.4 on 2024-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0049_alter_admin_roles_filter_options_app_job_pull_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_roles_filter',
            name='ROLE_NAME',
        ),
        migrations.AddField(
            model_name='admin_roles_filter',
            name='ROLE_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
