# Generated by Django 5.0.4 on 2024-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0050_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_roles_filter',
            name='SETUP_COMPLETE',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ALL_ROLES',
        ),
    ]
