# Generated by Django 5.0.4 on 2024-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0051_admin_roles_filter_setup_complete_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='provisioningpolicy',
            name='SETUP_COMPLETE',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
