# Generated by Django 4.2.11 on 2024-04-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0052_app_job_pull_friday_app_job_pull_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_pull',
            name='FRIDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='MONDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='SATURDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='SUNDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='THURSDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='TUESDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='app_job_pull',
            name='WEDNESDAY',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='FRIDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='MONDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='SATURDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='SUNDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='THURSDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='TUESDAY',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hr_job_pull',
            name='WEDNESDAY',
            field=models.BooleanField(default=False),
        ),
    ]
