# Generated by Django 5.0.4 on 2024-04-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0054_user_lockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_MAPPING_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(blank=True, max_length=128, null=True)),
                ('FIRST_NAME', models.CharField(blank=True, max_length=128, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=128, null=True)),
                ('ROLE', models.CharField(blank=True, max_length=128, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=128, null=True)),
                ('DATE_GRANTED', models.CharField(blank=True, max_length=128, null=True)),
                ('DATE_REVOKED', models.CharField(blank=True, max_length=128, null=True)),
                ('LAST_LOGIN', models.CharField(blank=True, max_length=128, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'CSV_MAPPING_TABLE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CSV_UPLOAD_FIELDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIELD_NAME', models.CharField(blank=True, max_length=128, null=True)),
                ('DATE', models.DateTimeField(blank=True, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'CSV_UPLOAD_FIELDS',
                'managed': True,
            },
        ),
    ]
