# Generated by Django 5.0.4 on 2024-05-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0056_alter_hr_job_pull_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCESSREQUEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REQUEST_ID', models.CharField(max_length=100, null=True)),
                ('APP_NAME', models.CharField(max_length=100, null=True)),
                ('REQUESTOR', models.CharField(max_length=100, null=True)),
                ('ROLES', models.CharField(max_length=1000, null=True)),
                ('BUSINESS_APPROVER', models.CharField(max_length=100, null=True)),
                ('IT_APPROVER', models.CharField(max_length=100, null=True)),
                ('DATE_REQUESTED', models.DateTimeField(null=True)),
                ('DATE_APPROVED', models.DateTimeField(null=True)),
                ('STATUS', models.CharField(max_length=100, null=True)),
                ('ASSIGNED_TO', models.CharField(max_length=100, null=True)),
                ('COMMENTS', models.CharField(max_length=1000, null=True)),
                ('REQUEST_TYPE', models.CharField(max_length=100, null=True)),
                ('PRIORITY', models.CharField(max_length=100, null=True)),
                ('COMPANY_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.company')),
            ],
            options={
                'db_table': 'ACCESS_REQUEST',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ACCESSREQUESTCOMMENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATOR', models.CharField(max_length=100, null=True)),
                ('COMMENT_DETAILS', models.CharField(max_length=100, null=True)),
                ('DATE_ADDED', models.DateTimeField(null=True)),
                ('REQUEST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.accessrequest')),
            ],
            options={
                'db_table': 'ACCESS_REQUEST_COMMENTS',
                'managed': True,
            },
        ),
    ]
