# Generated by Django 5.0.4 on 2024-05-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0058_accessrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='CREATOR',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
