# Generated by Django 5.0.4 on 2024-05-08 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0059_accessrequest_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='APPROVEL_TOKEN',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
