# Generated by Django 5.0.4 on 2024-05-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0060_accessrequest_approvel_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrequest',
            old_name='APPROVEL_TOKEN',
            new_name='APPROVAL_TOKEN',
        ),
    ]
