# Generated by Django 5.0.4 on 2024-05-09 17:11

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0064_alter_emailverification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='TOKEN',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
