# Generated by Django 5.0.4 on 2024-05-09 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0065_company_token_alter_emailverification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='TOKEN',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
