# Generated by Django 5.0.4 on 2024-05-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0067_app_record_token_alter_accessrequest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
