# Generated by Django 5.0.4 on 2024-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0068_requestidcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='DATE_REJECTED',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='REJECTION_REASON',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
