# Generated by Django 5.0.4 on 2024-05-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0069_accessrequest_date_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='DATE_GRANTED',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='GRANTED_BY',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
