# Generated by Django 5.0.4 on 2024-05-18 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0070_accessrequest_date_granted_accessrequest_granted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AUDITLIST',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PERIOD_END_DATE', models.DateField(blank=True, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
            ],
            options={
                'db_table': 'AUDIT_LIST',
                'managed': True,
            },
        ),
    ]
