# Generated by Django 5.0.4 on 2024-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0071_alter_accessrequest_id_auditlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='APP_DESCRIPTION',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
