# Generated by Django 5.0.6 on 2024-05-20 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0072_app_list_app_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUDITFILE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(blank=True, max_length=1000, null=True)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('CURRENTLY_WITH', models.CharField(blank=True, max_length=100, null=True)),
                ('FOLDER_NAME', models.CharField(blank=True, max_length=1000, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'AUDITFILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AUDITNOTES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditfile')),
            ],
            options={
                'db_table': 'AUDITNOTES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AUDITNOTESREPLY',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditfile')),
                ('OG_NOTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditnotes')),
            ],
            options={
                'db_table': 'AUDITNOTESREPLY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PREPARERSIGNOFF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PREPARER', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_SIGNEDOFF', models.DateTimeField(null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditfile')),
            ],
            options={
                'db_table': 'PREPARERSIGNOFF',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='REVIEWSIGNOFF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('REVIEWER', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_SIGNEDOFF', models.DateTimeField(null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditfile')),
            ],
            options={
                'db_table': 'REVIEWSIGNOFF',
                'managed': True,
            },
        ),
    ]
