# Generated by Django 5.0.6 on 2024-05-21 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0073_auditfile_auditnotes_auditnotesreply_preparersignoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORKPAPER_UPLOAD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.FileField(upload_to='workpapers')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
