# Generated by Django 5.0.6 on 2024-05-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0075_workpaper_upload_audit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpaper_upload',
            name='audit_id',
        ),
    ]
