# Generated by Django 5.0.6 on 2024-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0076_remove_workpaper_upload_audit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpaper_upload',
            name='audit_id',
            field=models.UUIDField(null=True),
        ),
    ]
