# Generated by Django 5.0.6 on 2024-05-22 06:17

import appAUDITAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0077_workpaper_upload_audit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='AUDIT_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workpaper_upload',
            name='file_name',
            field=models.FileField(upload_to=appAUDITAI.models.workpaper_upload_to),
        ),
    ]
