# Generated by Django 5.0.6 on 2024-05-22 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0079_auditfile_date_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditfile',
            name='FILE_NAME',
        ),
        migrations.AddField(
            model_name='auditfile',
            name='file_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.workpaper_upload'),
        ),
    ]
