# Generated by Django 5.0.6 on 2024-05-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0081_alter_auditfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpaper_upload',
            name='workpaper_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAUDITAI.workpaper_upload'),
        ),
    ]
