# Generated by Django 5.0.6 on 2024-05-23 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0082_workpaper_upload_workpaper_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpaper_upload',
            name='workpaper_id',
        ),
        migrations.AddField(
            model_name='auditfile',
            name='workpaper_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appAUDITAI.workpaper_upload'),
        ),
    ]
