# Generated by Django 5.0.6 on 2024-05-24 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0085_risklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskgeneral',
            name='RISK_RATING',
        ),
        migrations.CreateModel(
            name='RISKRATING',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RATING', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('RISK_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.risklist')),
            ],
            options={
                'db_table': 'RISKRATING',
                'managed': True,
            },
        ),
    ]
