# Generated by Django 5.0.6 on 2024-05-25 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0086_remove_riskgeneral_risk_rating_riskrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTROLLIST',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CONTROL_ID', models.CharField(blank=True, max_length=256, null=True)),
                ('CONTROL_TYPE', models.CharField(blank=True, max_length=256, null=True)),
                ('CONTROL_DESCRIPTION', models.CharField(blank=True, max_length=256, null=True)),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
            ],
            options={
                'db_table': 'CONTROLLIST',
                'managed': True,
            },
        ),
    ]
