# Generated by Django 5.0.6 on 2024-05-25 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0087_controllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RISK_MAPPING',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CONTROL_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.controllist')),
                ('RISK_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.riskrating')),
            ],
            options={
                'db_table': 'RISKCONTROLMATRIX',
                'managed': True,
            },
        ),
    ]
