# Generated by Django 5.0.6 on 2024-05-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0088_risk_mapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RISK_MAPPING',
            new_name='RISKMAPPING',
        ),
    ]
