# Generated by Django 5.0.6 on 2024-05-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0089_rename_risk_mapping_riskmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmapping',
            name='APP_NAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
    ]
