# Generated by Django 5.0.6 on 2024-05-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0090_riskmapping_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmapping',
            name='RISK_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.risklist'),
        ),
    ]
