# Generated by Django 5.0.6 on 2024-06-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0092_test_procedures_controllist_control_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_procedures',
            name='PHASE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='test_procedures',
            name='DESCRIPTION',
            field=models.TextField(blank=True, null=True),
        ),
    ]
