# Generated by Django 5.0.6 on 2024-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0099_test_procedures_control_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_procedures',
            name='PROCEDURE_NAME',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
