# Generated by Django 5.0.6 on 2024-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0100_test_procedures_procedure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_procedures',
            name='DEFAULT',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
