# Generated by Django 5.0.6 on 2024-06-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0102_design_evidence_design_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_testing',
            name='CONTROL_RATIONALE',
            field=models.TextField(blank=True, null=True),
        ),
    ]
