# Generated by Django 5.0.6 on 2024-06-04 19:55

import appAUDITAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0103_alter_design_testing_control_rationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_evidence',
            name='file_name',
            field=models.FileField(upload_to=appAUDITAI.models.design_evidence_folder),
        ),
    ]
