# Generated by Django 5.0.6 on 2024-06-04 23:28

import appAUDITAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0104_alter_design_evidence_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_evidence',
            name='file_name',
            field=models.FileField(max_length=256, upload_to=appAUDITAI.models.design_evidence_folder),
        ),
    ]
