# Generated by Django 5.0.6 on 2024-06-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0106_alter_design_evidence_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_testing',
            old_name='CONTROL_RATIONALE',
            new_name='CONTROL_CONCLUSION_RATIONALE',
        ),
    ]
