# Generated by Django 5.0.6 on 2024-06-06 03:21

import appAUDITAI.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0108_oe_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OE_EVIDENCE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.FileField(max_length=256, upload_to=appAUDITAI.models.oe_evidence_folder)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
                ('CONTROL_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.controllist')),
            ],
            options={
                'db_table': 'OE_EVIDENCE',
                'managed': True,
            },
        ),
    ]
