# Generated by Django 5.0.6 on 2024-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0109_oe_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='oe_testing',
            name='CONTROL_FREQUENCY',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='oe_testing',
            name='CONTROL_POPULATION',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='oe_testing',
            name='CONTROL_SAMPLES',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='oe_testing',
            name='PERIOD_END_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oe_testing',
            name='PERIOD_START_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
