# Generated by Django 5.0.6 on 2024-06-07 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0110_oe_testing_control_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_MANUAL_UPLOAD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.FileField(upload_to='manual_hr')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
