# Generated by Django 5.0.6 on 2024-06-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0111_hr_manual_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_manual_upload',
            name='file_name',
            field=models.FileField(upload_to='manualhrcvs'),
        ),
    ]
