# Generated by Django 5.0.6 on 2024-06-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0115_alpharegistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpharegistration',
            name='DATE_REGISTERED',
            field=models.DateField(blank=True, null=True),
        ),
    ]
