# Generated by Django 5.0.6 on 2024-06-16 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0116_alpharegistration_date_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AUDIT_ACCESS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ROLE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
                ('FILE_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.auditlist')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AUDIT_ACCESS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AUDITUSERS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ROLE', models.CharField(max_length=100, null=True)),
                ('COMPANY_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.company')),
            ],
        ),
    ]
