# Generated by Django 5.0.6 on 2024-06-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_list_sftp',
            name='AUTH_KEY',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
