# Generated by Django 5.1.3 on 2024-11-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequestapprover',
            name='APPROVER',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.hr_record')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.accessrequest')),
            ],
        ),
    ]
