# Generated by Django 5.1.3 on 2024-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0002_alter_accessrequestapprover_approver_approvaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
