# Generated by Django 5.0.6 on 2024-06-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0002_hr_list_sftp_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_job_pull',
            name='SCHEDULE_TIME',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
