# Generated by Django 5.1.3 on 2024-11-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0003_termination_process_term_notifyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='termination_process',
            name='PROCESS_DIFFERENCE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termination_process',
            name='PROCESS_DIFFERENCE_OTHER',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
