# Generated by Django 5.1.3 on 2024-11-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0003_approvaltoken_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
