# Generated by Django 5.0.6 on 2024-07-02 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0003_alter_hr_job_pull_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_DATA_UPLOAD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('emptype', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('datehired', models.DateField()),
                ('daterehired', models.DateField()),
                ('termdate', models.DateField()),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'HR_DATA_UPLOAD',
                'managed': True,
            },
        ),
    ]
