# Generated by Django 5.0.6 on 2024-07-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0004_hr_data_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HR_DATA_UPLOAD',
            new_name='HR_DATA_MAPPING',
        ),
    ]
