# Generated by Django 5.1.3 on 2024-11-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0005_alter_accessrequest_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='APP_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
