# Generated by Django 5.1.3 on 2024-11-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0006_alter_accessrequest_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='APP_NAME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.app_list'),
        ),
    ]
