# Generated by Django 5.0.6 on 2024-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0006_alter_hr_data_mapping_datehired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
