# Generated by Django 5.1.3 on 2024-11-21 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0007_alter_accessrequest_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequestapprover',
            name='APPROVED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_record'),
        ),
    ]
