# Generated by Django 5.0.6 on 2024-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0007_alter_hr_data_mapping_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_data_mapping',
            name='file_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
