# Generated by Django 5.0.6 on 2024-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0008_hr_data_mapping_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='datehired',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='daterehired',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='emptype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='jobtitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='manager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='termdate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_data_mapping',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
