# Generated by Django 5.1.3 on 2024-12-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0009_role_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_owners',
            name='ROLE_OWNERS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_record'),
        ),
    ]
