# Generated by Django 5.0.6 on 2024-07-07 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0009_alter_hr_data_mapping_datehired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_RECORD_IMPORT_LOG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('JOB_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('SOURCE_LINE_COUNT', models.CharField(blank=True, max_length=50, null=True)),
                ('DESTI_LINE_COUNT', models.CharField(blank=True, max_length=50, null=True)),
                ('JOB_COMPLETE', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'HR_IMPORT_LOG',
                'managed': True,
            },
        ),
    ]
