# Generated by Django 5.1.3 on 2024-12-15 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0010_alter_role_owners_role_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAR_FILE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('REVIEW_TAG', models.CharField(blank=True, max_length=100, null=True)),
                ('FREQUENCY', models.CharField(blank=True, max_length=100, null=True)),
                ('INTIATED_BY', models.CharField(blank=True, max_length=100, null=True)),
                ('INITIATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('REPORT_DATE', models.DateField(auto_now_add=True, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'UAR_FILE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UAR_DATA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('UAR_FILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.uar_file')),
            ],
            options={
                'db_table': 'UAR_DATA',
                'managed': True,
            },
        ),
    ]
