# Generated by Django 5.1.3 on 2024-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0011_uar_file_uar_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uar_file',
            name='INITIATED_ON',
        ),
        migrations.RemoveField(
            model_name='uar_file',
            name='INTIATED_BY',
        ),
        migrations.RemoveField(
            model_name='uar_file',
            name='REPORT_DATE',
        ),
        migrations.AddField(
            model_name='uar_data',
            name='INITIATED_ON',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uar_data',
            name='INTIATED_BY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uar_data',
            name='REPORT_DATE',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uar_file',
            name='START_DATE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
