# Generated by Django 5.0.6 on 2024-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0011_hr_record_import_log_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_record_import_log',
            name='UPLOADED_BY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_record_import_log',
            name='IMPORT_DATE',
            field=models.DateTimeField(),
        ),
    ]
