# Generated by Django 5.0.6 on 2024-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0013_app_list_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='DEVTYPE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
