# Generated by Django 5.1.3 on 2024-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0013_uar_file_days_to_complete_uar_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uar_file',
            name='STATUS',
            field=models.CharField(blank=True, default='Not Started', max_length=100, null=True),
        ),
    ]
