# Generated by Django 5.0.6 on 2024-07-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0014_app_list_devtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='DATABASE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='DB_VERSION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='NETWORK',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='NETWORK_VERSION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='OS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='OS_VERSION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
