# Generated by Django 5.1.3 on 2024-12-20 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0014_alter_uar_file_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uar_data',
            old_name='REPORT_DATE',
            new_name='REVIEW_COMPLETED_ON',
        ),
        migrations.AddField(
            model_name='uar_data',
            name='EMAIL_ADDRESS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.app_record'),
        ),
        migrations.AddField(
            model_name='uar_data',
            name='REVIEWED_BY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_record'),
        ),
        migrations.CreateModel(
            name='UAR_NOTES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CREATED_BY', models.CharField(blank=True, max_length=100, null=True)),
                ('REVIEW_COMMENTS', models.CharField(blank=True, max_length=100, null=True)),
                ('REVIEW_COMMENTS_DATE', models.DateField(auto_now_add=True, null=True)),
                ('REVIEW_NOTES_STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('UAR_DATA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.uar_file')),
            ],
            options={
                'db_table': 'UAR_NOTES',
                'managed': True,
            },
        ),
    ]
