# Generated by Django 5.1.3 on 2024-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0015_rename_report_date_uar_data_review_completed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uar_data',
            name='REVIEW_CYCLE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
