# Generated by Django 5.0.6 on 2024-07-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0015_app_list_database_app_list_db_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='PW_CONFIGURABLE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
