# Generated by Django 5.0.6 on 2024-07-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0016_app_list_pw_configurable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PASSWORD',
            new_name='APP_PASSWORD',
        ),
    ]
