# Generated by Django 5.1.3 on 2025-01-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0017_alpharegistration_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpharegistration',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
