# Generated by Django 5.0.6 on 2024-07-19 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0017_rename_password_app_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_record',
            name='TOKEN',
        ),
        migrations.AlterField(
            model_name='app_record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
