# Generated by Django 5.1.3 on 2025-01-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0018_alter_alpharegistration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpharegistration',
            name='COMPANY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alpharegistration',
            name='FIRST_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alpharegistration',
            name='LAST_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alpharegistration',
            name='REFERRER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
