# Generated by Django 5.0.6 on 2024-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0018_remove_app_record_token_alter_app_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_mapping_table',
            name='FILE',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csv_mapping_table',
            name='FILE_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
