# Generated by Django 5.0.6 on 2024-07-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0019_csv_mapping_table_file_csv_mapping_table_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_mapping_table',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
