# Generated by Django 5.1.3 on 2025-01-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0019_alter_alpharegistration_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user_sftp',
            name='SFTP_SECRET_HASHED',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
