# Generated by Django 5.1.3 on 2025-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0020_app_user_sftp_sftp_secret_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_pull',
            name='STATUS',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
