# Generated by Django 5.0.6 on 2024-07-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0020_csv_mapping_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_record',
            name='DATE_APPROVED',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='DATE_GRANTED',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='DATE_REVOKED',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='LAST_LOGIN',
            field=models.DateField(null=True),
        ),
    ]
