# Generated by Django 5.0.6 on 2024-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0021_alter_app_record_date_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_record',
            name='LAST_MODIFIED',
            field=models.DateField(auto_now_add=True),
        ),
    ]
