# Generated by Django 5.1.3 on 2025-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0022_job_alert_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user_sftp',
            name='PORT',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
