# Generated by Django 5.0.6 on 2024-07-22 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0022_alter_app_record_last_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_user_log',
            name='SOURCE_LINE_COUNT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='app_list',
            name='APPLICATION_OWNER',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='COMPANY_ID',
            field=models.ManyToManyField(blank=True, to='appAUDITAI.company'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='COMPANY_ID',
            field=models.ManyToManyField(blank=True, to='appAUDITAI.company'),
        ),
    ]
