# Generated by Django 5.1.3 on 2025-01-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0023_app_user_sftp_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_record',
            name='LAST_UPDATED',
            field=models.DateTimeField(null=True),
        ),
    ]
