# Generated by Django 5.0.6 on 2024-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0023_app_job_user_log_source_line_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_record_import_log',
            name='JOB_ERROR',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
