# Generated by Django 5.0.6 on 2024-07-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0024_hr_record_import_log_job_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_user_log',
            name='UPLOADED_BY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
