# Generated by Django 5.1.3 on 2025-01-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0024_app_record_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_user_log_process',
            name='JOB_NAME',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
