# Generated by Django 5.1.3 on 2025-01-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0025_app_job_user_log_process_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_list_sftp',
            name='PORT',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hr_list_sftp',
            name='SFTP_SECRET_HASHED',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
