# Generated by Django 5.0.6 on 2024-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0025_app_job_user_log_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_job_user_log',
            name='JOB_NAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
