# Generated by Django 5.0.6 on 2024-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0026_alter_app_job_user_log_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_job_user_log',
            name='JOB_DATE',
            field=models.DateField(null=True),
        ),
    ]
