# Generated by Django 5.1.3 on 2025-01-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0026_hr_list_sftp_port_hr_list_sftp_sftp_secret_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_job_pull',
            name='SCHEDULE_TIME',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
