# Generated by Django 5.0.6 on 2024-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0027_alter_app_job_user_log_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_job_user_log',
            name='CREATED_COUNT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
