# Generated by Django 5.1.3 on 2025-01-20 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0027_alter_hr_job_pull_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOB_ALERT_HR_RECIPIENT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RECIPIENT', models.CharField(blank=True, max_length=1000, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('JOB_NAME', models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.app_job_pull')),
            ],
            options={
                'db_table': 'JOB_ALERT_HR_RECIPIENT',
                'managed': True,
            },
        ),
    ]
