# Generated by Django 5.1.3 on 2025-01-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0028_job_alert_hr_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_alert_hr_recipient',
            name='APP_NAME',
        ),
        migrations.AlterField(
            model_name='job_alert_hr_recipient',
            name='JOB_NAME',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_job_pull'),
        ),
    ]
