# Generated by Django 5.0.6 on 2024-07-24 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0028_app_job_user_log_created_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROVISIONING_PROCESS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FORM', models.CharField(blank=True, max_length=100, null=True)),
                ('APPROVERS', models.CharField(blank=True, max_length=100, null=True)),
                ('APPROVERS_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('GRANTOR', models.CharField(blank=True, max_length=100, null=True)),
                ('GRANTOR_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('PROCESS_DIFFERENCE', models.CharField(blank=True, max_length=100, null=True)),
                ('PROCESS_DIFFERENCE_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('LAST_CERTIFIED', models.DateField(null=True)),
                ('CERTIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'PROVISIONING_PROCESS',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PROVISIONINGPOLICY',
        ),
    ]
