# Generated by Django 5.0.6 on 2024-07-26 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0029_provisioning_process_delete_provisioningpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioning_process',
            name='APPROVERS_OTHER',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provisioning_process',
            name='GRANTOR_OTHER',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='provisioning_process',
            name='PROCESS_DIFFERENCE_OTHER',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TERMINATION_PROCESS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NETWORK_RELIANCE', models.CharField(blank=True, max_length=100, null=True)),
                ('TIMELINESS', models.CharField(blank=True, max_length=100, null=True)),
                ('TERM_DOCUMENTATION', models.CharField(blank=True, max_length=100, null=True)),
                ('TERM_DOCUMENTATION_OTHER', models.CharField(blank=True, max_length=500, null=True)),
                ('TERM_PROCESS', models.CharField(blank=True, max_length=100, null=True)),
                ('TERM_AUTOMATED_DESC', models.CharField(blank=True, max_length=500, null=True)),
                ('DISABLE_TYPE', models.CharField(blank=True, max_length=500, null=True)),
                ('DISABLE_TYPE_OTHER', models.CharField(blank=True, max_length=500, null=True)),
                ('LAST_CERTIFIED', models.DateField(null=True)),
                ('CERTIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'TERMINATION_PROCESS',
                'managed': True,
            },
        ),
    ]
