# Generated by Django 5.1.3 on 2025-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0029_remove_job_alert_hr_recipient_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_record',
            name='LAST_REFRESHED',
            field=models.DateTimeField(null=True),
        ),
    ]
