# Generated by Django 5.0.6 on 2024-07-27 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0030_alter_provisioning_process_approvers_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAR_PROCESS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FREQUENCY', models.CharField(blank=True, max_length=100, null=True)),
                ('DAYS_TO_COMPLETE', models.CharField(blank=True, max_length=100, null=True)),
                ('SCOPE_USERS', models.CharField(blank=True, max_length=100, null=True)),
                ('SCOPE_ROLES', models.CharField(blank=True, max_length=100, null=True)),
                ('EXTRACTOR', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_TOOL', models.CharField(blank=True, max_length=10, null=True)),
                ('TOOL_NAME', models.CharField(blank=True, max_length=10, null=True)),
                ('EXTRACTION_SEND', models.CharField(blank=True, max_length=100, null=True)),
                ('EXTRACTION_SEND_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('REVIEWER', models.CharField(blank=True, max_length=100, null=True)),
                ('REVIEWER_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('CNA_REVIEWER', models.CharField(blank=True, max_length=100, null=True)),
                ('CNA_PROCESS', models.CharField(blank=True, max_length=1000, null=True)),
                ('CHANGE_DOCUMENTATION', models.CharField(blank=True, max_length=100, null=True)),
                ('CHANGE_DOCUMENTATION_SEND', models.CharField(blank=True, max_length=100, null=True)),
                ('CHANGE_DOCUMENTATION_SEND_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('CHANGE_TIMELINE', models.CharField(blank=True, max_length=100, null=True)),
                ('CHANGE_DOCUMENTATION_REVIEWED', models.CharField(blank=True, max_length=100, null=True)),
                ('SOD_CHECK', models.CharField(blank=True, max_length=100, null=True)),
                ('SOD_MITIGATION', models.CharField(blank=True, max_length=1000, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'UAR_PROCESS',
                'managed': True,
            },
        ),
    ]
