# Generated by Django 5.1.3 on 2025-01-20 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0030_hr_record_last_refreshed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NETWORK_AUTH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LDAP_SERVER', models.CharField(blank=True, max_length=128, null=True)),
                ('LDAP_PORT', models.CharField(blank=True, max_length=128, null=True)),
                ('BASE_DN', models.CharField(blank=True, max_length=128, null=True)),
                ('BIND_DN', models.CharField(blank=True, max_length=128, null=True)),
                ('LDAP_PW_HASHED', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'NETWORK_AUTH',
                'managed': True,
            },
        ),
    ]
