# Generated by Django 5.0.6 on 2024-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0031_uar_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='uar_process',
            name='SCOPE_EXEMPTED',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
