# Generated by Django 5.1.3 on 2025-01-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0031_network_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_auth',
            name='AUTO_TERMINATE_AD',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
