# Generated by Django 5.1.3 on 2025-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0032_network_auth_auto_terminate_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_record_import_log',
            name='FILE_NAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
