# Generated by Django 5.0.6 on 2024-07-28 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0032_uar_process_scope_exempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termination',
            name='CONTROL_ID',
        ),
        migrations.RemoveField(
            model_name='terminationpolicy',
            name='APP_NAME',
        ),
        migrations.CreateModel(
            name='PRIVILEGED_PROCESS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ADMIN_ROLES', models.CharField(blank=True, max_length=100, null=True)),
                ('CAPABILITIES', models.CharField(blank=True, max_length=100, null=True)),
                ('CAPABILITIES_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('ADMIN_REVIEW_PERFORMED', models.CharField(blank=True, max_length=50, null=True)),
                ('ADMIN_REVIEW_FREQUENCY', models.CharField(blank=True, max_length=100, null=True)),
                ('ADMIN_REVIEW_DOCUMENT', models.CharField(blank=True, max_length=100, null=True)),
                ('ADMIN_REVIEW_DOCUMENT_OTHER', models.CharField(blank=True, max_length=100, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
        ),
        migrations.DeleteModel(
            name='PROVISIONING',
        ),
        migrations.DeleteModel(
            name='TERMINATION',
        ),
        migrations.DeleteModel(
            name='TERMINATIONPOLICY',
        ),
    ]
