# Generated by Django 5.0.6 on 2024-07-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0033_remove_termination_control_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_list',
            old_name='SETUP_COMPLETE',
            new_name='SETUP_GENINFO',
        ),
        migrations.AddField(
            model_name='app_list',
            name='SETUP_PROCESS',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app_list',
            name='SETUP_USERDATA',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
