# Generated by Django 5.0.6 on 2024-07-30 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0034_rename_setup_complete_app_list_setup_geninfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPLIANCE_POPULATION',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CHECK_AUTH', models.BooleanField(blank=True, null=True)),
                ('CHECK_PROV', models.BooleanField(blank=True, null=True)),
                ('CHECK_TERMED', models.BooleanField(blank=True, null=True)),
                ('CHECK_UAR', models.BooleanField(blank=True, null=True)),
                ('CHECK_ADMIN', models.BooleanField(blank=True, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
            ],
            options={
                'db_table': 'COMPLIANCE_POPULATION',
                'managed': True,
            },
        ),
    ]
