# Generated by Django 5.0.6 on 2024-07-30 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0035_compliance_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance_population',
            name='CHECK_ADMIN',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliance_population',
            name='CHECK_AUTH',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliance_population',
            name='CHECK_PROV',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliance_population',
            name='CHECK_TERMED',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliance_population',
            name='CHECK_UAR',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='POLICY_PASSWORD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LENGTH', models.IntegerField(blank=True, null=True)),
                ('UPPER', models.BooleanField(default=False)),
                ('LOWER', models.BooleanField(default=False)),
                ('NUMBER', models.BooleanField(default=False)),
                ('SPECIAL_CHAR', models.BooleanField(default=False)),
                ('AGE', models.IntegerField(blank=True, null=True)),
                ('HISTORY', models.IntegerField(blank=True, null=True)),
                ('LOCKOUT_ATTEMPT', models.IntegerField(blank=True, null=True)),
                ('LOCKOUT_DURATION', models.CharField(blank=True, max_length=50, null=True)),
                ('MFA_ENABLED', models.BooleanField(default=False)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
            ],
        ),
    ]
