# Generated by Django 5.1.3 on 2025-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0035_remove_app_list_setup_userdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='SETUP_USERDATA',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_list',
            name='SETUP_GENINFO',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_list',
            name='SETUP_PROCESS',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_list',
            name='SETUP_ROLLOWNER',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
