# Generated by Django 5.0.6 on 2024-07-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0036_alter_compliance_population_check_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklist',
            name='REQUIRED',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risklist',
            name='RISK_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='risklist',
            name='RISK_DESCRIPTION',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='risklist',
            name='RISK_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='risklist',
            name='RISK_TYPE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
