# Generated by Django 5.1.3 on 2025-01-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0036_app_list_setup_userdata_alter_app_list_setup_geninfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_list',
            name='SOX_INSCOPE',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
