# Generated by Django 5.0.6 on 2024-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0037_risklist_required_risklist_risk_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklist',
            name='REQUIRED',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
