# Generated by Django 5.1.3 on 2025-01-27 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0037_app_list_sox_inscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAR_SOD_CHECK',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('REVIEW_CYCLE', models.CharField(blank=True, max_length=100, null=True)),
                ('WITH_SOD', models.BooleanField(default=False)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('EMAIL_ADDRESS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.app_record')),
                ('ROLE_OWNER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_record')),
                ('UAR_FILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.uar_file')),
            ],
            options={
                'db_table': 'UAR_SOD_CHECK',
                'managed': True,
            },
        ),
    ]
