# Generated by Django 5.1.3 on 2025-01-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0038_uar_sod_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uar_sod_check',
            old_name='WITH_SOD',
            new_name='WITH_SOD_VIOLATION',
        ),
    ]
