# Generated by Django 5.0.6 on 2024-08-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0038_alter_risklist_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controllist',
            name='COMPANY_ID',
        ),
        migrations.RemoveField(
            model_name='controllist',
            name='CONTROL_RELEVANCE',
        ),
    ]
