# Generated by Django 5.0.6 on 2024-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0039_remove_controllist_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllist',
            name='CONTROL_CATEGORY',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
