# Generated by Django 5.1.3 on 2025-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0039_rename_with_sod_uar_sod_check_with_sod_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uar_sod_check',
            name='ROLE_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
