# Generated by Django 5.1.3 on 2025-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0040_uar_sod_check_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uar_sod_check',
            name='EMAIL_ADDRESS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
