# Generated by Django 5.0.6 on 2024-08-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0040_controllist_control_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlist',
            old_name='FILE_NAME',
            new_name='AUDIT_ID',
        ),
        migrations.AddField(
            model_name='auditlist',
            name='AUDIT_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlist',
            name='AUDIT_TYPE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
