# Generated by Django 5.0.6 on 2024-08-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0041_rename_file_name_auditlist_audit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlist',
            name='AUDIT_DESCRIPTION',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
