# Generated by Django 5.1.3 on 2025-02-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0041_alter_uar_sod_check_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='uar_sod_check',
            name='INITIATED_ON',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='uar_sod_check',
            name='INTIATED_BY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uar_sod_check',
            name='REVIEWED_BY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uar_sod_check',
            name='REVIEW_COMPLETED_ON',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
