# Generated by Django 5.0.6 on 2024-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0042_auditlist_audit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmapping',
            name='RATING',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riskmapping',
            name='RATING_RATIONALE',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
