# Generated by Django 5.1.3 on 2025-02-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0042_uar_sod_check_initiated_on_uar_sod_check_intiated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uar_sod_check',
            name='INITIATED_ON',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uar_sod_check',
            name='REVIEW_COMPLETED_ON',
            field=models.DateField(blank=True, null=True),
        ),
    ]
