# Generated by Django 5.1.3 on 2025-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0043_alter_uar_sod_check_initiated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uar_sod_check',
            name='STATUS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
