# Generated by Django 5.0.6 on 2024-08-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0043_riskmapping_rating_riskmapping_rating_rationale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RISKRATING',
        ),
    ]
