# Generated by Django 5.1.3 on 2025-02-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0044_uar_sod_check_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN', models.CharField(max_length=255, unique=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('EXPIRES_AT', models.DateTimeField()),
                ('IS_USED', models.BooleanField(default=False)),
                ('ROLE_OWNER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.hr_record')),
                ('UAR_FILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.uar_file')),
            ],
        ),
    ]
