# Generated by Django 5.0.6 on 2024-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0044_delete_riskrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskmapping',
            name='CONTROL_ID',
        ),
        migrations.AddField(
            model_name='riskmapping',
            name='CONTROL_ID',
            field=models.ManyToManyField(blank=True, null=True, to='appAUDITAI.controllist'),
        ),
    ]
