# Generated by Django 5.1.3 on 2025-02-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0045_uareviewtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UAReviewToken',
            new_name='UAR_REVIEW_TOKEN',
        ),
    ]
