# Generated by Django 5.0.6 on 2024-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0045_remove_riskmapping_control_id_riskmapping_control_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmapping',
            name='CONTROL_ID',
            field=models.ManyToManyField(blank=True, to='appAUDITAI.controllist'),
        ),
    ]
