# Generated by Django 5.1.3 on 2025-02-11 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0046_rename_uareviewtoken_uar_review_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAR_INSCOPE_ROLES',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('REVIEW_CYCLE', models.CharField(blank=True, max_length=100, null=True)),
                ('ROLE_NAMES', models.TextField(blank=True, max_length=100000, null=True)),
                ('LAST_UPDATED', models.DateField(blank=True, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('UAR_FILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.uar_file')),
            ],
            options={
                'db_table': 'UAR_INSCOPE_ROLES',
                'managed': True,
            },
        ),
    ]
