# Generated by Django 5.0.6 on 2024-08-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0046_alter_riskmapping_control_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmapping',
            name='COMPANY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company'),
        ),
    ]
