# Generated by Django 5.1.3 on 2025-02-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0047_uar_inscope_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uar_inscope_roles',
            name='ROLE_NAMES',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
