# Generated by Django 5.0.6 on 2024-08-14 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0047_riskmapping_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditfile',
            old_name='AUDIT_ID',
            new_name='FILE_NAME',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='DATE_SENT',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='FOLDER_NAME',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='auditfile',
            name='APP_NAME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='COMPANY_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company'),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='PREPARER',
            field=models.ManyToManyField(blank=True, related_name='Preparer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='REVIEWER',
            field=models.ManyToManyField(blank=True, related_name='Reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='TYPE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
