# Generated by Django 5.1.3 on 2025-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0048_alter_uar_inscope_roles_role_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uar_inscope_roles',
            name='LAST_UPDATED',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
