# Generated by Django 5.0.6 on 2024-08-14 23:14

from django.db import migrations
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0048_rename_audit_id_auditfile_file_name_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='auditfile',
            name='FILE_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.RenameField(
            model_name='auditfile',
            old_name='FILE_NAME',
            new_name='TITLE',
        ),
    ]
