# Generated by Django 5.0.6 on 2024-08-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0049_rename_file_name_auditfile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='FOLDER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
