# Generated by Django 5.0.6 on 2024-08-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0050_auditfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='CONTROL_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.controllist'),
        ),
    ]
