# Generated by Django 5.0.6 on 2024-08-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0051_auditfile_control_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_procedures',
            name='CONTROL_ID',
        ),
        migrations.AddField(
            model_name='test_procedures',
            name='DOMAIN',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
