# Generated by Django 5.0.6 on 2024-08-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0052_remove_test_procedures_control_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_procedures',
            old_name='DESIGN_PROCEDURES',
            new_name='PHASE',
        ),
        migrations.RenameField(
            model_name='test_procedures',
            old_name='INTERIM_PROCEDURES',
            new_name='PROCEDURE_DETAILS',
        ),
        migrations.RemoveField(
            model_name='test_procedures',
            name='ROLLFORWARD_PROCEDURES',
        ),
    ]
