# Generated by Django 5.0.6 on 2024-08-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0053_rename_design_procedures_test_procedures_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_procedures',
            name='CONTROL_TITLE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appAUDITAI.controllist'),
        ),
    ]
