# Generated by Django 5.0.6 on 2024-08-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0054_test_procedures_control_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_procedures',
            name='PROCEDURE_NAME',
        ),
    ]
