# Generated by Django 5.0.6 on 2024-08-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0055_remove_test_procedures_procedure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_procedures',
            name='DOMAIN',
        ),
        migrations.RemoveField(
            model_name='test_procedures',
            name='PHASE',
        ),
        migrations.RemoveField(
            model_name='test_procedures',
            name='TYPE',
        ),
    ]
