# Generated by Django 5.0.6 on 2024-08-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0056_remove_test_procedures_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_procedures',
            name='PHASE',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
