# Generated by Django 5.0.6 on 2024-08-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0057_test_procedures_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_procedures',
            old_name='CONTROL_TITLE',
            new_name='CONTROL_ID',
        ),
    ]
