# Generated by Django 5.0.6 on 2024-08-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0058_rename_control_title_test_procedures_control_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_procedures',
            name='PHASE',
        ),
        migrations.AddField(
            model_name='test_procedures',
            name='DESIGN_PROCEDURES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_procedures',
            name='FINAL_PROCEDURES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_procedures',
            name='INTERIM_PROCEDURES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test_procedures',
            name='ROLLFORWARD_PROCEDURES',
            field=models.TextField(blank=True, null=True),
        ),
    ]
