# Generated by Django 5.0.6 on 2024-10-04 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0059_remove_test_procedures_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORKPAPER_DETAILS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DESIGN_PROCEDURES', models.TextField(blank=True, null=True)),
                ('DESIGN_RESULT', models.TextField(blank=True, null=True)),
                ('DESIGN_EVIDENCE', models.TextField(blank=True, null=True)),
                ('DESIGN_CONCLUSION', models.CharField(blank=True, max_length=25, null=True)),
                ('DESIGN_CONCLUSION_RATIONALE', models.TextField(blank=True, null=True)),
                ('INTERIM_APPLICABLE', models.CharField(blank=True, max_length=25, null=True)),
                ('INTERIM_POPULATION', models.CharField(blank=True, max_length=25, null=True)),
                ('INTERIM_POPULATION_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('INTERIM_SAMPLES', models.CharField(blank=True, max_length=25, null=True)),
                ('INTERIM_SAMPLING_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('INTERIM_PROCEDURES', models.TextField(blank=True, null=True)),
                ('INTERIM_RESULT', models.TextField(blank=True, null=True)),
                ('INTERIM_EVIDENCE', models.TextField(blank=True, null=True)),
                ('INTERIM_CONCLUSION', models.CharField(blank=True, max_length=25, null=True)),
                ('INTERIM_CONCLUSION_RATIONALE', models.TextField(blank=True, null=True)),
                ('RF_APPLICABLE', models.CharField(blank=True, max_length=25, null=True)),
                ('RF_POPULATION', models.CharField(blank=True, max_length=25, null=True)),
                ('RF_POPULATION_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('RF_SAMPLES', models.CharField(blank=True, max_length=25, null=True)),
                ('RF_SAMPLING_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('RF_PROCEDURES', models.TextField(blank=True, null=True)),
                ('RF_RESULT', models.TextField(blank=True, null=True)),
                ('RF_EVIDENCE', models.TextField(blank=True, null=True)),
                ('RF_CONCLUSION', models.CharField(blank=True, max_length=25, null=True)),
                ('RF_CONCLUSION_RATIONALE', models.TextField(blank=True, null=True)),
                ('FINAL_APPLICABLE', models.CharField(blank=True, max_length=25, null=True)),
                ('FINAL_POPULATION', models.CharField(blank=True, max_length=25, null=True)),
                ('FINAL_POPULATION_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('FINAL_SAMPLES', models.CharField(blank=True, max_length=25, null=True)),
                ('FINAL_SAMPLING_RATIONALE', models.CharField(blank=True, max_length=1000, null=True)),
                ('FINAL_PROCEDURES', models.TextField(blank=True, null=True)),
                ('FINAL_RESULT', models.TextField(blank=True, null=True)),
                ('FINAL_EVIDENCE', models.TextField(blank=True, null=True)),
                ('FINAL_CONCLUSION', models.CharField(blank=True, max_length=25, null=True)),
                ('FINAL_CONCLUSION_RATIONALE', models.TextField(blank=True, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list')),
                ('COMPANY_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company')),
                ('CONTROL_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.controllist')),
            ],
            options={
                'db_table': 'WORKPAPER_DETAILS',
                'managed': True,
            },
        ),
    ]
