from django.contrib import admin

from .models import HR_RECORD, APP_RECORD, CSV,SAP_USR02,APP_LIST, POLICIES, CONTROLS, COMPANY, MULTIPLE_COMPANY, USERROLES,PASSWORD,PWCONFIGATTACHMENTS
from .models import OE_EVIDENCE, OE_TESTING, DESIGN_EVIDENCE,DESIGN_TESTING,TEST_PROCEDURES,CONTROLLIST, RISKMAPPING,RISKRATING,RISKLIST,RISKGENERAL,RISKDETAILS,AUDITFILE,WORKPAPER_UPLOAD,AUDITLIST, ACCESSREQUESTCOMMENTS,EmailVerification,UserToken,ACCESSREQUEST, HR_JOB_PULL,HR_LIST_SFTP,USER_LOCKOUT,PROVISIONINGPOLICY,PASSWORDPOLICY,TERMINATIONPOLICY,APP_USER_UPLOAD, APP_NEW_USER_APPROVAL, ADMIN_ROLES_FILTER,PASSWORDCONFIG,APP_USER_SFTP,APP_JOB_PULL,APP_JOB_USER_LOG,APP_JOB_USER_LOG_PROCESS,HR_LIST_SFTP,HR_JOB_PULL,HR_JOB_USER_LOG
# Register your models here.
admin.site.register(HR_RECORD)
admin.site.register(APP_RECORD)
admin.site.register(CSV)
admin.site.register(SAP_USR02)
admin.site.register(APP_LIST)
admin.site.register(POLICIES)
admin.site.register(COMPANY)
admin.site.register(MULTIPLE_COMPANY)
admin.site.register(USERROLES)
admin.site.register(PASSWORD)
admin.site.register(PWCONFIGATTACHMENTS)
admin.site.register(PASSWORDPOLICY)
admin.site.register(TERMINATIONPOLICY)
admin.site.register(APP_USER_UPLOAD)
admin.site.register(APP_NEW_USER_APPROVAL)
admin.site.register(ADMIN_ROLES_FILTER)
admin.site.register(PASSWORDCONFIG)
admin.site.register(APP_USER_SFTP)
admin.site.register(APP_JOB_PULL)
admin.site.register(APP_JOB_USER_LOG)
admin.site.register(APP_JOB_USER_LOG_PROCESS)
admin.site.register(PROVISIONINGPOLICY)
admin.site.register(USER_LOCKOUT)
admin.site.register(HR_LIST_SFTP)
admin.site.register(HR_JOB_PULL)
admin.site.register(ACCESSREQUEST)
admin.site.register(UserToken)
admin.site.register(EmailVerification)
admin.site.register(ACCESSREQUESTCOMMENTS)
admin.site.register(AUDITLIST)
admin.site.register(WORKPAPER_UPLOAD)
admin.site.register(AUDITFILE)
admin.site.register(RISKGENERAL)
admin.site.register(RISKDETAILS)
admin.site.register(CONTROLS)
admin.site.register(RISKLIST)
admin.site.register(RISKRATING)
admin.site.register(RISKMAPPING)
admin.site.register(CONTROLLIST)
admin.site.register(TEST_PROCEDURES)
admin.site.register(DESIGN_TESTING)
admin.site.register(DESIGN_EVIDENCE)
admin.site.register(OE_TESTING)
admin.site.register(OE_EVIDENCE)



